[package]
name = "slow-sleuth"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = { version = "0" }
tracing-subscriber = { version = "0", features = ["std"] }